= GROW REST API GUIDE
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===


[[overview-errors]]
== 오류

에러 응답이 발생했을 때 (상태 코드 >= 400), 본문에 해당 문제를 기술한 JSON 객체가 담겨있다. 에러 객체는 다음의 구조를 따른다.

include::

예를 들어, 잘못된 요청으로 이벤트를 만들려고 했을 때 다음과 같은 `400 Bad Request` 응답을 받는다.

include::

[[resources]]
= 리소스

[[resources-exercise-create]]
=== 운동 정보 생성

'POST' 요청을 사용해서 운동 정보를 등록할 수 있다.

operation::create-exercise[snippets='response-fields,curl-request,http-request,http-response,request-body,response-body,response-fields']

[[resources-exercise-get]]
=== 운동 정보 가져오기

'GET' 요청을 사용해서 운동 정보를 가져올 수 있다.

operation::get-exercise[snippets='curl-request,response-body,response-fields']

[[resources-routine-create]]
=== 루틴 기본 정보 생성

'POST' 요청을 사용해서 루틴 정보를 등록할 수 있다.

operation::create-routine[snippets='response-fields,curl-request,http-request,http-response,request-body,response-body,response-fields']

[[resources-routine-get]]
=== 루틴 정보 가져오기

'GET' 요청을 사용해서 루틴 정보를 등록할 수 있다.

operation::get-routine[snippets='curl-request,http-request,request-body,http-response,response-body,response-fields']

[[resources-add-exercise-routine]]
=== 루틴에 운동 정보 등록하기

'POST' 요청을 사용해서 운동 정보를 루틴에 등록할 수 있다.

operation::add exercise to routine[snippets='curl-request,http-request,request-body,http-response,response-body,response-fields']

[[resources-get-routine-full-infromation]]
=== 루틴 상세 정보 가져오기

'GET' 요청을 사용해서 루틴에 대한 모든 정보를 가져온다.

operation::get-routine-full-information[snippets='curl-request,http-request,request-body,http-response,response-body,response-fields']

[[resources-create-routine-category]]
=== 운동 카테고리를 생성한다.

'POST' 요청을 사용해서 루틴카테고리를 등록한다.

operation::create-routine-category[snippets='curl-request,http-request,request-body,http-response,response-body,response-fields']

[[resources-add-routine-to-category]]
=== 루틴 카테고리에 루틴을 등록한다.

'POST' 요청을 사용해서 루틴카테고리에 루틴을 등록한다.

operation::add routine to category[snippets='curl-request,http-request,request-body,http-response,response-body,response-fields']

[[resources-get-category-with-routines-info]]
=== 루틴 카테고리 상세정보를 가져온다.

'GET' 요청을 사용해서 루틴카테고리 정보를 가져온다.

operation::get category with routines info[snippets='curl-request,http-request,request-body,http-response,response-body,response-fields']